docs/typeorm.md
typeorm 라이브러리 문서 업데이트
- 정의 : 한글화
- TypeORM만의 특징 작성
- datamapper 패턴 지원
- 쿼리빌더
=> Docs: typeorm.md 정의 및 특징 업데이트

src/modules/comment/comment.service.ts
대댓글 생성 API에
- 게시글 작성자
- 대댓글이 달리는 댓글 || 대댓글 작성자
에게 알림 생성이 없던 상황
```ts
const t = await this._dbService.getTransaction();
await t.startTransaction();
try {
const reply = await this._commentRepository.createComment(replyEntity);
await this._commentRepository.increaseReplyCount(parentId);
await this._postService.increaseCommentCount(post.id);
// 대댓글 작성자의 게시글이 아니라면, 게시글 작성자에게 알림을 생성한다. 👈
if (!user.isMy(post))
await this._notificationService.createByTargetUser(
user,
post.userId,
reply.id,
"comment"
);
// 대댓글 작성자의 (대)댓글이 아니라면, (대)댓글 작성자에게 알림 생성한다. 👈
if (!user.isMy(replyTarget))
await this._notificationService.createByTargetUser(
user,
replyTarget.userId,
reply.id,
"reply"
);
await t.commitTransaction();
return new ReplyResponseDto(reply, user);
```
Notification 인자명이 혼란스러운 것 같아요
```
// …
```
=> Add: comment service 대댓글 작성에 알림 추가

docs/class-validator.md
class-validator 라이브러리 문서 업데이트
Ref: #96
=> Docs: update class-validator.md

src/core/container.core.ts
inversifyJS 컨테이너의 기본 scope은 `inTransientScope`인데,
이는 종속성 해결시 같은 클래스의 인스턴스도 매번 새로 생성한다.
예를 들어 A가 B, C에 의존하고 B, C가 D에 의존할때,
```
A -> B, C -> D
```
`inTransientScope`에서 B와 C는 메모리상에서 서로 다른 D 인스턴스를 참조한다.
```
A -> B -> D1
A -> C -> D2
```
이를 `Singleton`으로 수정하여 해결할 수 있다.
```ts
const container = new Container();
```
```ts
const container = new Container({ defaultScope: "Singleton" });
```
참고 #106
=> Update: container 옵션 singleton scope로 수정

README.md, docker-compose.dev.yml, docs/dev-with-docker.md, src/core/database/redis.service.ts, src/datasource.ts
개발환경 도커 컴포즈 추가
- 레디스 환경에 따라 url 수정
- TypeORM 동기화 옵션 환경에 따라 수정
- 저희가 개발할땐 false로 수정해서 사용하면 될 것 같아요
- 이제 엔티티,테이블 수정에 대해서는 마이그레이션 사용해야할 듯
- 개발환경 docker compose 추가
`main` 브랜치에 머지되면 도커 허브로 이미지 빌드후 push 하는 CI 만들 예정
Ref: #70
=> Add: 개발 환경 docker compose

src/core/container.core.ts, src/core/types.core.ts, src/modules/comment/comment.service.ts, src/modules/comment/interfaces/IComment.service.ts, src/modules/index.controller.ts, src/modules/post/interfaces/IPost.service.ts, src/modules/post/post.service.ts, src/modules/report/dto/index.ts, src/modules/report/dto/report.dto.ts, src/modules/report/entity/report.entity.ts, src/modules/report/helper/report-target-type-transforemr.ts, src/modules/report/interfaces/IReport.repository.ts, src/modules/report/interfaces/IReport.service.ts, src/modules/report/report.controller.ts, src/modules/report/report.module.ts, src/modules/report/report.repository.ts, src/modules/report/report.service.ts, src/shared/api/discord-api.service.ts, src/shared/api/interfaces/IApi-webhook.service.ts, src/shared/enum.shared.ts
댓글 또는 게시글에 대한 신고 API
다음 메서드 구현해야합니당
이 PR 머지 된 후, PR 나눠서 진행할 예정이에요
report entity의 reason 컬럼이 varchar(255)인데 max값이 초과되어 수정 함
```ts
@Column({ nullable: true, comment: "신고사유 (max: 300)" })
```
```ts
@Column({ nullable: true, comment: "신고사유 (max: 200)", length: 200 })
```
=> Feat: 신고 API

src/core/container.core.ts, src/core/types.core.ts, src/modules/like/dto/like-response.dto.ts, src/modules/post/interfaces/IPost.repository.ts, src/modules/post/post.repository.ts, src/modules/post/post.service.ts, src/modules/trend/entity/trend.entity.ts, src/modules/trend/interfaces/ITrend.service.ts, src/modules/trend/interfaces/ITrendRepository.ts, src/modules/trend/trend.module.ts, src/modules/trend/trend.repository.ts, src/modules/trend/trend.service.ts, src/shared/constant.shared.ts
- 인기글 구현
- post 에서 조회수 증가 구현
- 게시글 타입이 `post` 이고, 게시글 조회수가 10 이상, 게시글 좋아요 수가 3 이상이면, 인기글로 등록하도록 설정
- 인기글의 조건은 상수로 둬서 언제든 변경 가능
pr 머지된 이후 구현할 작업
- [like response 익명일 경우 userNickname null로 반환되도록 변경](https://github.com/MBTI-Channel/server/commit/c29fa247bd32f787af14e4834db5b42c1d23871b)
- [post service 변수명 틀린거 변경](https://github.com/MBTI-Channel/server/commit/001faebf3abf0a4a1f0416f4244f7df95fe9b813)
=> Feat: trend 생성

src/config/index.ts, src/shared/api/discord-api.service.ts
새로운 신고 생성시 디스코드 신고 채널에 알림 발송
- config에 discord report web hook url 추가
- discord webhook service에 pushReportNotification 구현
Ref: #121
=> Feat: 신고 디스코드 알림

src/modules/comment/comment.service.ts, src/modules/report/report.service.ts
다른 서비스와 소통활때 사용하는 IsValid 메서드 구현
- 자기 자신에대한 신고시 BadRequest 예외가 터지는데, 메세지를 작성하지 않아서 추가함
Ref: #121
=> Feat: comment is valid 메서드

src/modules/post/interfaces/IPost.repository.ts, src/modules/post/post.repository.ts, src/modules/post/post.service.ts
게시글 신고수 증가 구현
다음 두 메서드를 추가 및 구현
- post repository : increaseReportCount
- post service  : increaseReportCount
Ref: #121
=> Feat: 게시글 신고수 증가

src/swagger/openapi.yaml, src/swagger/paths/reports/index.yaml, src/swagger/responses/reports/index.post.yaml
신고 생성 API에 대한 swagger 작성
Ref: #121
=> Docs: swagger 신고 API 추가

src/modules/user/dto/index.ts, src/modules/user/dto/update-user-nickname.dto.ts, src/modules/user/interfaces/IUser.service.ts, src/modules/user/user.controller.ts, src/modules/user/user.service.ts
유저 닉네임 업데이트 API
기획 상 닉네임 수정에는 기간 제한이 없다하여 로직에 넣지 않았습니다
=> Feat: 닉네임 업데이트 API

docs/README.md, docs/dev-with-docker.md
docs 업데이트
docs/README.md 
- 링크 작성
- 문서 내용 추가
docs/dev-with-docker.md
- 문서 업데이트(설명 추가)
=> Docs: docs 업데이트

src/swagger/openapi.yaml, src/swagger/paths/comments/id.yaml, src/swagger/paths/comments/index.yaml, src/swagger/paths/comments/replies.yaml, src/swagger/responses/comments/index.get.yaml, src/swagger/responses/comments/index.post.yaml, src/swagger/responses/comments/replies.get.yaml, src/swagger/responses/comments/replies.post.yaml
댓글 API swagger 설명 부실 및 실제 요청, 응답과 다른 항목이 많은 상황
swagger 댓글 api 문서 다음 항목과 같이 수정함
- 전체적인 댓글 API 설명 개선
- 실제 요청, 응답과 동일하게 수정
=> Fix: swagger 댓글 API 전체적으로 수정

src/modules/comment/comment.repository.ts
더미데이터 약 천만건 이상에서 페이징조회가 50초~1분 이상이 소요되는 문제가 발견
* PK 정렬로 수정하여 조회 속도 개선
```ts
.orderBy(`comment.createdAt`, "DESC")
```
```ts
.orderBy(`comment.id`, "DESC")
```
Related to: #89
=> Refactor: 유저 작성 댓글 order id로 수정

src/swagger/paths/users/logout.yaml, src/swagger/responses/users/logout.delete.yaml
기존의 swagger 로그아웃 api 문서를 개선
- 요청에 설명 추가
- 응답 쪽 현재 코드에 맞게 수정
=> Docs: swagger 로그아웃 api 개선

src/migrations/1660457303391-create-base-category.ts
- category 테이블에 기본 카테고리 insert하기 위해 추가
```ts
public async up(queryRunner: QueryRunner): Promise<void> {
const BASE_CATEGORIES = [
"mbti",
"love",
"school",
"workLife",
"music",
"movie",
"trip",
"hobby",
];
const repository = await queryRunner.connection.getRepository(Category);
// 1. 모든 카테고리 low 조회
const categories = await repository.find({
select: ["name"],
});
// 2. BASE_CATEGORIES 배열 돌면서 없는 low INSERT
BASE_CATEGORIES.forEach(async (e) => {
const foundCategory = categories.find((c) => c.name === e);
if (!foundCategory) await repository.insert({ name: e });
});
}
```
=> Chore: 기본 카테고리 마이그레이션 추가

src/swagger/openapi.yaml, src/swagger/paths/posts/id.yaml, src/swagger/paths/posts/index.yaml, src/swagger/paths/posts/trending.yaml, src/swagger/responses/posts/id.delete.yaml, src/swagger/responses/posts/id.get.yaml, src/swagger/responses/posts/id.patch.yaml, src/swagger/responses/posts/index.get.yaml, src/swagger/responses/posts/index.post.yaml, src/swagger/responses/posts/trending.get.yaml
swagger post api 개선
- 설명 상세하게 수정 개선
- 누락값 추가
- 잘못된 예시 타입 수정
- 검색 부분은 추후 수정
=> Docs: update swagger post

src/swagger/paths/posts/search.yaml
searchOption을 dto에 추가함
searchOption swagger에 반영
=> Docs: swagger post search

src/modules/bookmark/bookmark.repository.ts, src/modules/bookmark/bookmark.service.ts, src/modules/bookmark/dto/bookmark-post-response.dto.ts, src/modules/bookmark/interfaces/IBookmark.repository.ts, src/modules/bookmark/interfaces/IBookmark.service.ts, src/modules/update-log/update-log.service.ts, src/modules/user/user.controller.ts
북마크한글 조회 API 구현
- bookmark 리포지토리 findAllByUserId 구현
- bookmark 서비스 getAllByUser 구현
- bookmark BookmarkPostResponseDto 추가
`BookmarkPostResponseDto` 너무 무거워 보이는데 좋은 방법이 있을련지..
=> Feat: 북마크한 글 조회 API

src/modules/post/dto/post-response.dto.ts, src/swagger/responses/posts/id.get.yaml, src/swagger/responses/posts/id.patch.yaml, src/swagger/responses/posts/index.get.yaml, src/swagger/responses/posts/index.post.yaml, src/swagger/responses/posts/search.get.yaml, src/swagger/responses/posts/trending.get.yaml
`isActiveUser` 필드값이 필요없다고 생각되어 지움
- post.response.dto에서 `isActiveUser` 제거
- swagger 수정
=> Update: post response

src/modules/auth/auth.service.ts, src/modules/login-log/login-log.service.ts
레포지토리 주입 코드 중 구현체가 직접 주입되는 곳을 발견
구현체 주입은 DIP를 위반하므로 인터페이스 주입으로 수정
=> Fix: 구현체 주입 수정

src/swagger/openapi.yaml, src/swagger/paths/users/bookmarks.yaml, src/swagger/responses/users/bookmarks.get.yaml, src/swagger/responses/users/posts.get.yaml
북마크한글 조회 API swagger 작성
- 내 게시글 조회 swagger 문서에 isAcitveUser 필드 제거
=> Docs: swagger 북마크한글 조회 API 추가

src/swagger/openapi.yaml, src/swagger/paths/users/me.mbti.yaml, src/swagger/responses/users/me.mbti.patch.yaml
유저 MBTI 업데이트 API에 대한 swagger 작성
=> Docs: swagger 유저 MBTI 업데이트 API 추가

src/modules/post/dto/create-post.dto.ts, src/modules/post/interfaces/IPost.service.ts, src/modules/post/post.controller.ts, src/modules/post/post.service.ts, src/swagger/paths/posts/index.yaml
post create dto 필드에 imagesUrl로 사진 url을 넘겨줌
- 확장성을 고려하여 imagesUrl -> filesUrl로 수정
- swagger 수정
=> Update: swagger post create

src/modules/file/file.repository.ts, src/modules/file/file.service.ts, src/modules/file/interfaces/IFile.repository.ts, src/modules/file/interfaces/IFile.service.ts, src/modules/post/post.controller.ts, src/modules/post/post.service.ts
게시글 삭제시 게시글의 파일 삭제를 위한 기능
- file delete 기능 구현
=> Add: file delete

src/modules/auth/auth.service.ts, src/modules/auth/interfaces/IAuth.service.ts, src/modules/user/interfaces/IUser.service.ts, src/modules/user/user.service.ts
user service 주석, 로그 개선
- user service 인터페이스 주석 설명 추가
- user service 주석, 로그 개선
- auth service `getRefreshKey` 추가
```ts
const key = `${id}-${userAgent}`
```
이코드가 반복되고 문자열이다보니 실수가 일어날 수 있으므로 메서드 추가함
커밋은 많은데 작업사항 내용만 보시면 됩니다
=> Refactor: user service 주석, 로그 개선

src/modules/auth/auth.service.ts, src/modules/auth/interfaces/IAuth.service.ts, src/modules/auth/interfaces/IOauth.service.ts, src/modules/auth/oauth.service.ts, src/modules/user/user.service.ts
- auth service 주석, 로그 개선
- 주석, 로그 개선
- 변수명 수정
=> Refactor: auth service 주석, 로그 개선

src/modules/file/file.repository.ts, src/modules/file/file.service.ts, src/modules/file/interfaces/IFile.repository.ts, src/modules/file/interfaces/IFile.service.ts, src/modules/post/dto/create-post.dto.ts, src/modules/post/dto/update-post.dto.ts, src/modules/post/interfaces/IPost.service.ts, src/modules/post/post.controller.ts, src/modules/post/post.service.ts, src/swagger/paths/posts/id.yaml, src/swagger/paths/posts/index.yaml
게시글 수정시 file에 대한 처리가 필요
- dto에서 filesUrl IsOptional -> IsNotEmpty로 수정
- 넣을 파일이 없다면 빈 배열로 넣어주기
- updatePostDto에 filesUrl 추가
- fileUpdate 작성
- 기존에 있는 파일url과 입력된 파일 url과 비교하여 db에 존재하지 않는 파일 url이면 새로 생성
- db에 존재하는데, 입력된 파일 url에 없으면 삭제 (TODO)
- swagger 작성
게시글 업데이트 시 file 업데이트 관련해서 처리를 해줬는데,
삭제해야 할 파일에 대한 처리에서 막혀 TODO로 냅뒀습니다.
작업하면서 커밋을 날리다보니 처음 커밋한 내용이 수정되는 경우도 있네요..ㅠ
=> Feat: file update
