- src/modules/comment/comment.service.ts
- src/modules/comment/dto/create-reply.dto.ts
- src/modules/comment/entity/comment.entity.ts
- src/modules/comment/interfaces/IComment.repository.ts
- src/modules/comment/interfaces/IComment.service.ts
- src/swagger/paths/comments/replies.yaml
- src/swagger/responses/comments/replies.post.yaml
대댓글 작성 API의 알림 기능 추가전 다음 내용들의 수정이 필요했습니다.
- 대댓글 대상 `taggedId` not null로 수정하기
- CommentService.createReply 로직 개선하기
이전에 @FaberJoo님과 대댓글 작성 로직 회의에서 내용은 
```
parentId - 부모댓글
taggedId - 태그할 댓글 대상 null 가능
```
- `taggedId`를 null로 요청할 경우, 부모 댓글에 대한 대댓글이고
- `taggedId`가 notnull로 요청할 경우, 대댓글에 대한 대댓글 작성이었는데요.
이는 `taggedId` `parentId`를 동일하게 요청하면 안되는데, 예외사항이 하나 더 추가되어서 다음과 같이 수정했습니다.
```
parentId - 부모댓글
taggedId - 태그할 댓글 대상 null 안됨
```
```ts
// parentId === taggedId라면 부모 댓글에 대한 대댓글 작성이다.
if (parentId === taggedId) {
...
if(taggedTarget.parentId) throw new BadReqeustException(`invalid parent comment id`);
```
이 방법보다
```ts
// parentId === taggedId라면 부모 댓글에 대한 대댓글 작성이다.
if (parentId === taggedId) {
...
if(taggedTarget.isReply()) throw new BadReqeustException(`invalid parent comment id`);
```
"아  대댓글 대상인 …
> Update: 대댓글 작성 taggedId NOT NULL로 수정, 로직 개선

- src/modules/notifications/dto/notification-response.dto.ts
- src/modules/notifications/entity/notification.entity.ts
- src/modules/notifications/helper/notification-type-transformer.ts
Notification의
- type 컬럼 타입 tinyint 
- type 엔티티 타입 string
불일치를 매핑하기 위해 static함수 `typeTo`, `typeFrom`을 사용함
TypeORM의 ValueTransformer 인터페이스를 구현한 클래스를 만든후,
Column 옵션 중 transformer에 사용함
```ts
@Column({
nullable: false,
type: "tinyint",
comment: "알림 종류[1:comment 2:reply 3:likes 4:trend 5:notice]",
})
type: number;
// of 메서드
notification.type = Notification.typeTo(type);
// 응답 dto
this.type = Notification.typeFrom(entity.type);
```
- static함수 `typeTo`, `typeFrom` 제거
```
@Column({
nullable: false,
type: "tinyint",
transformer: new NotificationTypeTransformer(),
comment: "알림 종류[1:comment 2:reply 3:likes 4:trend 5:notice]",
})
type: number | NotificationType;
// of 메서드
notification.type = type
// 응답 dto
this.type = entity.type as NotificationType;
```
posts 쪽도 적용이 필요한데 누가할까요??
> Add: 알림 type transformer

- test/unit/modules/comment/comment.service.test.ts
CommentService.createReply 케이스가 많아서 테스트코드로 검증이 필요하다고 생각했습니다.
* 추가한 테스트 케이스:
* Success: 내가 작성한 부모 댓글에 대한 대댓글 작성. 게시글 작성자에게만 알림 발생
* Success: 내가 작성한 게시글 대한 대댓글 작성. 대댓글 대상 작성자에게만 알림 발생
* Error: 존재하지 않는 post id, NotFoundError 발생
* Error: 존재하지 않는 부모 댓글, NotFoundError 발생
* Error: parent id가 부모 댓글이 아니라면 BadReqeustException 발생
* Error: 존재하지 않는 대댓글, NotFoundError 발생
* Error: 대댓글의 parentId가 요청 parentId와 다르다면, BadReqeustException 발생
> Test: 대댓글 작성 service 테스트코드 추가

- src/modules/bookmark/bookmark.service.ts
- src/modules/bookmark/dto/bookmark-response.dto.ts
- src/modules/post/dto/post-response.dto.ts
- src/modules/post/entity/post.entity.ts
- src/modules/post/helper/post-type-transformer.ts
- src/modules/post/post.service.ts
Post의
- type 컬럼 타입 tinyint 
- type 엔티티 타입 string
불일치를 매핑하기 위해 static함수 `typeTo`, `typeFrom`을 사용함
TypeORM의 ValueTransformer 인터페이스를 구현한 클래스를 만든후,
Column 옵션 중 transformer에 사용함
```
let postType = Post.typeTo(PostType.POST);
if (category.name === CategoryName.MBTI) {
postType = Post.typeTo(PostType.MBTI);
}
```
```
let postType = PostType.POST;
if (category.name === CategoryName.MBTI) {
postType = PostType.MBTI;
}
```
> Add: post type transformer

- src/modules/comment/comment.repository.ts
- src/modules/comment/comment.service.ts
- src/modules/comment/interfaces/IComment.repository.ts
- src/modules/comment/interfaces/IComment.service.ts
- src/modules/like/dto/delete-like.dto.ts
- src/modules/like/interfaces/ILike.repository.ts
- src/modules/like/interfaces/ILike.service.ts
- src/modules/like/like.controller.ts
- src/modules/like/like.repository.ts
- src/modules/like/like.service.ts
- src/modules/post/interfaces/IPost.repository.ts
- src/modules/post/interfaces/IPost.service.ts
- src/modules/post/post.repository.ts
- src/modules/post/post.service.ts
- 좋아요 삭제 API 개발
- delete like API 작성
- deleteLikedto 작성
- post, comment 부분에 `decreaseLikeCount` 로직 생성
- 하나의 함수에서 처리하던 방식에서 함수를 나눠서 진행
- createLike 내에서 모든 작업 실행
- `checkId`, `checkMbti` 함수를 만들어 아이디와 mbti 유효성 검사 진행
- `deleteLike` 함수에서 재사용 가능
> Feat: delete like API

- docker-compose.dev.yml
- src/config/index.ts
- src/core/database/redis.service.ts
- redis 연결시 production인지 development인지 확인하고, redis.host, redis.port, redis.username, redis.password 통해서 연결
- 간단히 .env에 redisUrl 을 넣어줘 간결화 및 개발용과 배포용을 config할 때 부터 분리
- 환경변수를 클라이언트 쪽에서 가지고 있으니까 docker-compose 에서 environment 부분은 필요 없을꺼같은데 어떻게 생각하시나용?
> Update: redis url env

- src/modules/comment/comment.controller.ts
- src/modules/comment/comment.repository.ts
- src/modules/comment/comment.service.ts
- src/modules/comment/interfaces/IComment.repository.ts
- src/modules/comment/interfaces/IComment.service.ts
더미데이터 약 천만건 이상에서 페이징조회가 50초~1분 이상이 소요되는 문제가 발견
* pageInfoDto: itemsPerPage인자 maxResults로 수정하여 잘못된 전체 페이지 계산 수정
* 쿼리빌더 api getManyAndCount->getMany로 수정하여 COUNT 쿼리 제거
* totalCount: COUNT 쿼리반환값에서 post 엔티티의 comment count값으로 수정
https://github.com/MBTI-Channel/server/issues/89#issuecomment-1210491906 에서 정리했듯이
생성순으로 조회는 `4초이상` -> `1초미만 ms`로 개선했어요
좋아요 순으로 정렬할 경우에는 인덱스를 타지않고 전체 댓글 low조회 후 정렬하는 듯 합니다.
속도가 여전히 느리네요..
> Update: 댓글 조회 API 페이지네이션 수정

- src/modules/comment/comment.service.ts
- src/modules/post/post.service.ts
- src/shared/page/dto/page-info.dto.ts
```ts
totalCount === 0 ? 1 : Math.ceil(totalCount / itemsPerPage);
```
PageInfoDto의 생성자의 `totalCount` 계산식에서, 분모 `itemsPerPage`는 코드상에서 실제로는 페이지당 출력 수인 `maxResults`를 넣고 있는 상태.
페이지당 아이템 수라는 `itemsPerPage`이름과 실제 들어가는  maxResults 뜻이 맞지 않았다.
PageInfoDto 인스턴스를 만들때, `itemsPerPage`에는 `totalCount`계산을 위해 `maxResults`값이 들어갔다.
```ts
constructor(totalCount: number, itemsPerPage: number, currentPage: number)  {
this.totalCount = totalCount;
this.itemsPerPage = itemsPerPage;
this.currentPage = currentPage;
this.totalPage =
totalCount === 0 ? 1 : Math.ceil(totalCount / itemsPerPage);
}
```
```ts
export class PageInfoDto {
totalCount: number;
itemsPerPage: number;
currentPage: number;
totalPage: number;
/**
* @param totalCount   전체 아이템 수
* @param itemsPerPage 페이지당 아이템 수
* @param currentPage  현재 페이지
* …
```
> Update: page info dto 변수명에 맞게 수정

- src/core/database/interfaces/IRedis.service.ts
- src/core/database/redis.service.ts
- src/core/types.core.ts
- src/middlewares/middleware.module.ts
- src/middlewares/validate-access-refresh-token.middleware.ts
- src/modules/auth/auth.service.ts
- src/modules/auth/interfaces/IAuth.service.ts
- src/modules/comment/comment.repository.ts
- src/modules/user/interfaces/IUser.service.ts
- src/modules/user/user.controller.ts
- src/modules/user/user.service.ts
회원 탈퇴 API
- access, refresh token 검증 미들웨어 추가
- redis 키로 데이터 삭제 메서드 추가
- 유저 탈퇴 API 구현
- 새로 추가된 미들웨어, `RedisService.del()`은 PR을 나누려 했으나 머지시간까지 걸릴 것같아 부득이하게 같이 PR을 올렸습니다
- 스웨거는 머지된 후 따로 PR 작성 예정
> Fea: 회원 탈퇴 API

- src/modules/comment/comment.service.ts
- src/modules/notifications/notification.service.ts
- src/modules/post/interfaces/IPost.repository.ts
- src/modules/post/post.repository.ts
- src/modules/post/post.service.ts
- src/shared/page/dto/page-infinite-scroll-info.dto.ts
5천만개의 더미 데이터로 테스트 해본 결과 페이징 조회가 1분 이상 소요됨. 
- PageInfiniteScrollInfoDto 에서 totalCount 제거
- TypeORM findAndCount 대신 find 사용 
- 인기게시글 조회를 하고 싶을 때, `where { isTrend: true }` 로 인기게시글인 것을 받아오는데, 5천만개의 더미 데이터중 인기게시글이 maxResults보다 적으면, 처음부터 끝까지 돌아서 시간이 오래걸린다..
- 자잘한 오류 발견했는데, 머지 후 고치도록 할게요
- `skip = offset take =limit` skip은 일반 페이지에서 사용하자~
issue: #89
> Update: posts pagination

- src/modules/user/user.controller.ts
회원가입 API에서 쿠키에 refresh 설정을 안해주는걸 발견
- 쿠키 세팅 코드 추가함
- 쿠키 옵션 secure 환경변수에 따라 동적으로 변하게 수정
> Fix: 회원가입 API 쿠키에 Refresh 설정 추가

- src/modules/user/interfaces/IUser.service.ts
- src/modules/user/user.controller.ts
- src/modules/user/user.service.ts
로그아웃 API 구현
로그아웃 API 구현
- access token, refresh token 필요
- 레디스에 보관한 refresh 상테 삭제
- 클라이언트 쿠키 refresh 삭제
swagger는 회원 탈퇴 API와 함께 PR 나눠서 진행하겠습니당
> Feat: 로그아웃 API

- src/modules/post/dto/get-all-post.dto.ts
- src/modules/post/dto/get-trend.dto.ts
- src/modules/post/dto/search-post.dto.ts
- src/modules/post/interfaces/IPost.repository.ts
- src/modules/post/post.repository.ts
- src/modules/post/post.service.ts
post pagination이 무한스크롤 방식인데, skip을 사용하고 있었음
- skip 대신 nextId보다 작은 범위 내에서 검색하도록 where절 수정
- nextId 구하는 로직 변경
- post.dto 에서 skip 제거
> Update: post pagination nextId

- src/modules/post/post.controller.ts
- src/modules/post/post.repository.ts
startId가 1 이하일 경우 가져올 수 있는 데이터가 없음
- startId가 1 이하일 경우에는 전체 데이터에서 가져오도록 수정
- 게시글 상세 조회 잘못된 미들웨어 수정
조건문이 마음에 들진 않지만.. 추후 리펙토링에서 간단하게 바꿀 수 있는건 바꾸자..
> Update: post pagination where 동적으로 처리

- src/migrations/1660457303391-create-base-category.ts
마이그레이션 `create-base-category` 실행 도중, INSERT가 끝나지 않았는데 마이그레이션 커밋이 완료된 상태.
덕분에 Pool이 닫힌 상태에서 추가적인 비동기 쿼리가 날아가 에러가 터지는 상황
- forEach를 for of로 변경하여 해결 
- Promise.all은 순서보장이 안되는데, 카테고리 id 순서가 중요하기 때문에 속도가 느리더라도 for of사용함
참고
[[JS] forEach 함수는 async 함수를 기다려주지 않는다](https://constructionsite.tistory.com/43)
> Fix: create-base-category 마이그레이션 동기화 문제

- src/modules/category/entity/category.entity.ts
- src/modules/post/post.repository.ts
- src/shared/enum.shared.ts
enum에 정의된 카테고리 이름 임의로 되어있음
- figma에 맞추어 categoryName enum 수정
`In` 을 통해  카테고리를 확인했는데, 카테고리 개수가 많아지는 것을 고려하여, `Not`을 붙임
search 로직을 다시 보는데 수정이 필요한듯 하다.. 이 pr 머지된 이후 수정할 예정
> Update: category name

- src/modules/post/interfaces/IPost.repository.ts
- src/modules/post/post.repository.ts
- src/modules/post/post.service.ts
search 부분이 복잡해서 주석이 필요함
- 각 분기마다 어떤 상황인지 주석 담
- `searchInCategory`, `searchAll` 안써서 삭제
- `searchAllWithMbti` 본인의 mbti게시판 포함 전체 게시글 검색 새로 생성
모든 search마다 동적 where 조건이 있는데, 가독성에서 좋지는 않다고 느낀다.
추후 리펙토링이 가능하면 좋을 듯.  
추가로 검색이 현재는 제목에서만 찾고 있는데, 이 부분 추후에 바꿀 예정입니다.
> Update: category search

- src/modules/post/dto/create-post.dto.ts
- src/modules/post/interfaces/IPost.service.ts
- src/modules/post/post.controller.ts
- src/modules/post/post.service.ts
- src/swagger/paths/posts/index.yaml
post create dto에서 category가 Id로 전달되는 상황, 다른 dto와의 통일성을 위해 수정해줬다.
- `create-post-dto`에서 categoryId -> categoryName으로 수정
- 변경 사항 스웨거에 적용
> Refactor: post create dto

- src/modules/category/entity/category.entity.ts
- src/modules/post/dto/search-post.dto.ts
- src/modules/post/interfaces/IPost.repository.ts
- src/modules/post/post.repository.ts
- src/modules/post/post.service.ts
- src/shared/enum.shared.ts
검색 옵션으로 값을 찾을 때 제목만 기준으로 찾고 있었음
- searchOption enum추가
- 검색 옵션에 맞게 whereOption을 만들어주는 함수 작성
- 카테고리 선택 후 검색하는 함수 작성
제목만 기준으로 쿼리문을 작성함
검색 옵션에 따라 동적으로 처리 가능한 함수 작성
아래와 같이 사용하도록 변경
> Update: post search

- src/core/container.core.ts
- src/core/types.core.ts
- src/migrations/1660664316256-create-upate-log-table.ts
- src/modules/update-log/entity/update-log.entity.ts
- src/modules/update-log/interfaces/IUpdate-log.repository.ts
- src/modules/update-log/interfaces/IUpdate-log.service.ts
- src/modules/update-log/update-log.module.ts
- src/modules/update-log/update-log.repository.ts
- src/modules/update-log/update-log.service.ts
- src/modules/user/dto/index.ts
- src/modules/user/dto/udpate-user-mbti.dto.ts
- src/modules/user/entity/user.entity.ts
- src/modules/user/interfaces/IUser.service.ts
- src/modules/user/user.controller.ts
- src/modules/user/user.service.ts
- src/shared/enum.shared.ts
- src/shared/type.shared.ts
유저 MBTI 업데이트 API
- update log module 추가
- update log 테이블 생성 마이그레이션 추가
- UpdateLogType에 따른 마지막 update log를 조회하는 `findLastOneByType` 구현
- update log 생성 구현
- user mbti 업데이트 api 구현
- swagger는 PR 나눠서 작성할 예정
> Feat: 유저 MBTI 업데이트 API

- src/modules/comment/comment.service.ts
- src/swagger/responses/comments/replies.get.yaml
comment 테이블이 비어있는 상태에서 대댓글 조회시 에러가 터지는 상황
- 버그수정 : 빈 배열일시 404 에러
- nextId 로직 수정
- 만약 요청 maxResults가 10인데, 조회된 대댓글 결과가 3개라면, nextId가 null이어야 한다.
- 하지만 조회된 마지막 대댓글 id를 응답해서, 대댓글 결과 < maxResults라면, nextId 에 null 할당으로 수정
- 위 두사항에 대한 대댓글 조회 swagger 반영
```ts
const replyArray = await this._commentRepository.findAllReplies(
pageOptionsDto
);
const nextId = replyArray[replyArray.length - 1].id; // replyArray가 빈배열[] 라면 Error !!
```
```ts
const replyArray = await this._commentRepository.findAllReplies(
pageOptionsDto
);
// 아무런 대댓글 없으면 NotFoundException
if (replyArray.length === 0)
throw new NotFoundException(
`there are no replies to parent comment id ${pageOptionsDto.parentId}`
);
// replyArray길이가 maxResults보다 작다면 nextId는 null, 아니라면 마지막 idx의 id 할당
let nextId: number | null;
if (replyArray.length < …
```
> !HOTFIX: 대댓글 조회 버그 

- src/modules/comment/comment.repository.ts
- src/modules/comment/comment.service.ts
- src/modules/comment/interfaces/IComment.repository.ts
- 게시글 댓글 조회시 `items`는 비어있는데, `totalCount`를 post 테이블의 `commentCount` 컬럼으로 설정해서 값이 불일치하는 상황
```json
{
"pageInfo": {
"totalCount": 11,
"itemsPerPage": 0,
"currentPage": 1,
"totalPage": 1
},
"items": []
}
```
- `getManyAndCount` 성능의 이유로 `getMany`로 바꾸었으나 다시 `getManyAndCount`로 수정
```ts
const commentArray = await this._commentRepository.findAllComments(
pageOptionsDto
);
// 페이지 정보
const pageInfoDto = new PageInfoDto(
foundPost.commentCount,
commentArray.length,
page,
maxResults
```
```ts
const [commentArray, totalCount] =
await this._commentRepository.findAllComments(pageOptionsDto);
// 페이지 정보
const pageInfoDto = new PageInfoDto(
totalCount,
commentArray.length,
page,
maxResults
```
> Fix: 댓글 조회시 totalCount 값 불일치 수정

- src/modules/post/post.service.ts
- src/swagger/responses/posts/index.get.yaml
- src/swagger/responses/posts/search.get.yaml
- src/swagger/responses/posts/trending.get.yaml
post 테이블이 비어있는 상태에서 게시글 조회시 에러가 터지는 상황
- 전체 게시글 조회시 nextId 수정
- 인기글 조회시 nextId 수정
- 게시글 검색시 nextId 수정
- 404 NotFound 추가
- swagger 수정
> !HOTFIX: 게시글 조회 버그

- package.json
- package.json의 script 중 마이그레이션 명령어가 typeorm 글로벌 설치가 안되어있으면 실행하지 못하는 상황
* global typeorm 설치 없이 가능하게 수정함
> Chore: package.json 마이그레이션 script 로컬에서 적용되게 수정

- src/modules/bookmark/bookmark.controller.ts
- src/modules/bookmark/bookmark.service.ts
- src/modules/bookmark/interfaces/IBookmark.service.ts
- src/modules/comment/comment.controller.ts
- src/modules/comment/comment.service.ts
- src/modules/comment/interfaces/IComment.service.ts
- src/modules/like/interfaces/ILike.service.ts
- src/modules/like/like.controller.ts
- src/modules/like/like.service.ts
- src/modules/post/interfaces/IPost.service.ts
- src/modules/post/post.controller.ts
- src/modules/post/post.service.ts
삭제 메소드이름이 `remove`, `delete`로 나뉘는 상황
- `delete` -> `remove`로 수정
https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Operators/delete
- 자바스크립트는 delete 연산자 때문에 함수, 변수이름에 delete를 못쓰는데, 메소드에는 되네요..
암튼 위와 같은 이유가 있어서 remove로 선택했어요
- like쪽은 `deleteLike`라서 일단 냅두었습니다. 코멘트 달아주셔서 통일할지 의견 부탁드려요!
- 다음은 리포지토리 `remove` 리턴을 void에서 boolean으로 수정할 예정입니다
> Refactor: 삭제 메소드 이름 통합

- src/modules/notifications/interfaces/INotification.service.ts
- src/modules/notifications/notification.controller.ts
- src/modules/notifications/notification.repository.ts
- src/modules/notifications/notification.service.ts
notification  service `find all` 메서드의 next id 로직 수정이 필요한 상황
- next id 로직 수정
- `findAll` -> `getAllByUser`로 수정
- notification  service 주석, 로그 개선
```ts
// 다음 알림 페이지 있는지 확인
let nextId = null;
if (notificationArray.length === pageOptionsDto.maxResults + 1) {
nextId = notificationArray[notificationArray.length - 1].id;
notificationArray.pop();
}
```
레포지토리
```ts
.take(pageOptionsDto.maxResults + 1) // nextId를 위한 +1
```
```ts
// notificationArray 길이가 maxResults보다 작다면 nextId는 null, 아니라면 마지막 idx의 id 할당
let nextId: number | null;
if (notificationArray.length < pageOptionsDto.maxResults) nextId = null;
else nextId = notificationArray[notificationArray.length - 1].id;
```
레포지토리
```ts
.take(pageOptionsDto.maxResults)
```
- 예외처리에 조건문에 대해 추적하려고 log를 추가하다보니 주석이랑 겹치는 것 같아서
겹치는 부분에 대해서는 log를 우선시 했습니당
> Update: notification service 조회 next id 로직

- src/modules/user/user.controller.ts
- production 환경에서 백엔드 api로 oauth 요청 방지하기
`NODE_ENV`값이 `production`이라면 다음 get mapping 404응답으로 수정
```ts
// 임시 kakao 라우터
@httpGet("/kakao")
async kakaoLogin(req: Request, res: Response) {
if (process.env.NODE_ENV === "production") return res.status(404).end();
const url = `https://kauth.kakao.com/oauth/authorize?client_id=${config.kakao.restApiKey}&redirect_uri=${config.kakao.redirectUri}&response_type=code`;
return res.redirect(url);
}
// 임시 naver 라우터
@httpGet("/naver")
async naverLogin(req: Request, res: Response) {
if (process.env.NODE_ENV === "production") return res.status(404).end();
const url = `https://nid.naver.com/oauth2.0/authorize?response_type=code&client_id=${config.naver.clientId}&redirect_uri=${config.naver.redirectUri}&state=${config.naver.randomState}`;
return …
```
> Add: user controller oauth 로그인 배포 환경에서 접근 방지

- src/modules/notifications/dto/index.ts
- src/modules/notifications/dto/notification-page-response.dto.ts
- src/modules/notifications/interfaces/INotification.repository.ts
- src/modules/notifications/notification.repository.ts
- src/modules/notifications/notification.service.ts
- src/swagger/responses/notifications/index.get.yaml
- 알림 조회 API는 no offset 방식이라서 다음 페이지 요청마다 안읽은 알림수`totalCount`가 바뀌는 상황
- `PageResponseDto` 상속하여 `totalUnreadCount` 필드를 추가한 `NotificationPageResponseDto` 추가
- notification repository에 `countUnreadByUserId` 추가
- swagger 수정
리턴
```ts
return new PageResponseDto(
pageInfoDto,
notificationArray.map((e) => new NotificationResponseDto(e))
);
```
- `totalUnreadCount` 필드를 추가한 `NotificationPageResponseDto`로 리턴
```ts
return new NotificationPageResponseDto(
totalUnreadCount,
pageInfoDto,
notificationArray.map((e) => new NotificationResponseDto(e))
);
```
- 알림 정보 조회전, user의 안읽은 알림수가 0이라면 바로 return
```ts
const totalUnreadCount =
await this._notificationRepository.countUnreadByUserId(user.id);
// totalUnreadCount가 0이면 조회하지않고 바로 응답
if (totalUnreadCount === 0) {
this._log(`totalUnreadCountt is 0, so return …
```
> Fix: user 알림 조회 API

- src/middlewares/check-login-status.middleware.ts
* 클라이언트 측에서 미로그인여도 Authorization : Bearer null 헤더로 항상 넘어오는 상태
```ts
detail = async (accessToken, id) => {
try {
const res = await this.board.get(`posts/${id}`, {
headers: {
Authorization: `Bearer ${accessToken}`,
},
});
return res;
} catch (e) {
console.log(e);
}
};
```
- `CheckLoginStatus` 미들웨어에서 `Authorization: Bearer null`인 상황 체크
```ts
// accessToken이 없다면 미로그인 상태. next 호출
if (!accessToken) {
this._log(`not logged in. call next`);
return next();
}
```
```ts
// accessToken이 없거나 "null"이라면 미로그인 상태이므로 next를 호출한다.
// 프론트에서 로그인 안해도 인증 헤더가 넘어옵니다 (Authorization : Bearer null)
if (!accessToken || accessToken === "null") {
this._log(`not logged in. call next`);
return next();
}
```
> Fix: CheckLoginStatus 미들웨어 요청 인증 헤더에서 null일 경우 추가

- src/modules/user/interfaces/IUser.repository.ts
- src/modules/user/user.repository.ts
- src/modules/user/user.service.ts
- repo update 코드들이 통일되어있지 않는 상황
- update 쿼리 이후 findOne 쿼리를 더 수행하는 상황
- user repo update 이후 findOne제거. update 성공 유무를 return
- user service쪽 user update의 리턴이 boolean으로 바뀌었음으로 로직 수정
- 기존엔 update에 findOneById가 포함되어 user 엔티티를 리턴했음
```ts
const updatedUser = await userRepository.updqte(...);
```
- boolean hasUpdated 값에따라 NotFoundException 처리
```ts
this._log(`check if the update request was successful`);
const hasUpdated = await this._userRepository.update(...);
if (!hasUpdated) throw new NotFoundException("not exists user");
```
- 이후 access token 재발급이 필요할때 기존 user에 재할당함
```ts
user.mbti = mbti;
```
`이후 access token 재발급이 필요할때 기존 user에 재할당함`
- 엔티티에 직접 할당이 일어나는게 괜찮은지..
- 아니면 update이후 service에서 repo.findOneby를 다시 요청하는지..
- 아니면 close후 기존을 유지하여 repo.update에 findOneById로 통일하든지
어떤 방향으로 갈지 궁금합니다
> Update: user repo update 수정후 user service에 적용

- src/modules/post/interfaces/IPost.repository.ts
- src/modules/post/interfaces/IPost.service.ts
- src/modules/post/post.controller.ts
- src/modules/post/post.repository.ts
- src/modules/post/post.service.ts
- src/swagger/responses/posts/id.patch.yaml
기존: 게시글 수정시 게시글 전체 필드 응답
- update시 업데이트된 게시글 정보 받아오는 쿼리문 제거
- `post.repository.update` return타입 boolean으로 수정
- 게시글 수정시 응답 `{ updatedId: number }` 으로 수정
- swagger 수정
> Update: post patch

- src/modules/file/file.service.ts
fileDelete 할 때 값이 없으면 오류 발생
- file이 발견된 경우만 삭제하도록 수정
> Fix: file delete

- src/modules/post/dto/index.ts
- src/modules/post/dto/response/post-detail-response.dto.ts
- src/modules/post/dto/response/post-response.dto.ts
- src/modules/post/interfaces/IPost.service.ts
- src/modules/post/post.service.ts
- src/swagger/responses/posts/id.get.yaml
프론트 부분에서 게시글을 상세조회 할 때 유저가 게시글을 좋아요 했는지, 북마크 했는지 여부를 요구해서 수정
기존에 `PostResponseDto` 로 반환하던걸 `PostDetailResponseDto` 를 새로 만들어 반환함
이 과정에서 dto에 response 폴더를 생성하여 dto 요청과 응답을 분리
swagger 수정
- 이런식으로 쿼리를 또 날리면서 게시글 좋아요나 북마크 여부를 가져오는게 맞는지 모르겠다.
- 다시 보니까 like 부분은 리펙토링이 꽤 많이 필요해 보이네.. 추후에 수정 필수!!
> Update: 게시글 상세조회 
